on:
  push:
    branches: [main, master]
  pull_request:

name: format-check.yaml

permissions: read-all

jobs:
  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
